---
AWSTemplateFormatVersion: 2010-09-09


Parameters:

  ClusterStackName:
    Type: String

  AdminRoleArn:
    Type: String

  AdminUser:
    Type: String

  LambdaBucket:
    Type: String


Resources:

  AwsAuthConfigMapConfigCustomResourceLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: handler.zip
      Handler: main
      Role: !Ref AdminRoleArn
      Runtime: go1.x
      Timeout: 300

  AwsAuthConfigMapConfigCustomResource:
    Type: Custom::AwsAuthConfigMapConfigCustomResource
    Properties:
      ServiceToken: !GetAtt AwsAuthConfigMapConfigCustomResourceLambda.Arn
      AdminRoleArn: !Ref AdminRoleArn
      ClusterName:
        Fn::ImportValue: !Sub ${ClusterStackName}-ClusterName
      ClusterEndpoint:
        Fn::ImportValue: !Sub ${ClusterStackName}-ClusterEndpoint
      NodeInstanceRoleArn:
        Fn::ImportValue: !Sub ${ClusterStackName}-NodeInstanceRoleArn
      CodeBuildServiceRoleArn:
        Fn::ImportValue: !Sub ${ClusterStackName}-CodeBuildServiceRoleArn
      AdminUser: !Ref AdminUser
      AccountId: !Ref AWS::AccountId
    DependsOn:
      - AwsAuthConfigMapConfigCustomResourceLambda



